### PR TITLE
(GH-6) Added Cake.Recipe

### PR DESCRIPTION
**Pull request by RLittlesII**
This pull request is to resolve issue #6.  I have added the following.

- Added bootstrapper
- Added setup.cake
- Added nuspec conventions

### CODE REVIEW

**Comment by RLittlesII** [comment]
There are also environment variables needed to automate MyGet and NuGet package deployment.  I added the place holders, just need to populate the url's and api keys.

**Comment by RLittlesII** [comment]
@devlead Updated.  Green light on the build.  Let me know if there are any other missed particulars.

**Comment by devlead** [comment]
I think @gep13 has set the variables "server-side".

**Comment by gep13** [comment]
@devlead yes, that is correct.

**Comment by RLittlesII** [comment]
@devlead @gep13 are we good or is there something else needed to satisfy the resolution of the issue?  Seems like we are good.

**Comment by devlead** [comment]
@RLittlesII you can remove the env place holders as so they don't interfere with the ones configured on AppVeyor. Then I'll take it for a spin and merge if all's OK.

**Comment by RLittlesII** [comment]
@devlead Key's are yours.  It sticks in second gear. 😉

**Comment by devlead** [comment]
@RLittlesII  your changes have been merged, thanks for your contribution 👍

**Pull request merged**
